### ISSUE TITLE
Sorting broken now?

### ISSUE THREAD

**Issue by jansendotsh** [garrettjj/comic-management#3]
Implemented a successfully working autotag mechanism although it broke sorting. This appears to be created by the imported libraries although the stack trace below shows that it's an error generated the os.path.join in ln 157 of https://github.com/garrettjj/comic-management/blob/testing/comictool.py

```
(comic-management) garrett@DESKTOP-2IRDSCC:/mnt/c/Users/Garrett/Documents/GitHub/comic-management$ python3 ./comictool.py -s
Currently sorting 3 of Grass Kings, published by Boom! Studios in May, 2017.

Traceback (most recent call last):
  File "./comictool.py", line 256, in <module>
    main()
  File "./comictool.py", line 253, in main
    sorting(targetDir, workDir)
  File "./comictool.py", line 177, in __init__
    sorting.comicParser(self, file, targetDir, workDir)
  File "./comictool.py", line 157, in comicParser
    comicPath = os.path.join(targetDir, comicPublisher, comicSeries + " (" + comicVolume + ")")
  File "/mnt/c/Users/Garrett/Documents/GitHub/comic-management/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/mnt/c/Users/Garrett/Documents/GitHub/comic-management/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

I'm not totally sure how to resolve this and keep all functionality in place if "join" is going to throw an error whenever os.path.join is called. Likely going to need to steep on this one and look for review.

**Comment by jansendotsh** [comment]
This was really dumb and I just wasn't error checking the targetDir variable. Since it was set to None, python considered it a valid response when using try. Opted for using `if targetDir is None:` instead which seems to resolve.
